stages:
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./nginx.yaml
- name: Status
  steps:
  - runScriptConfig:
      image: kubectl
      shellScript: kubectl get pods
timeout: 60
notification: {}
